version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hsipl206
      MYSQL_PASSWORD: hsipl206
      MYSQL_DATABASE: hsipl
      security_opt:
        seccomp:unconfined
      # volumes:
      #   /var/lib/docker/volumes/myvolume/_data
    ports:
      - 3307:3306
    networks:
      - account_net


  backend:
    build: .
    restart: always
    environment:
      MODE: dev
      PORT: 6969

    links:
      - db
    ports:
      - 6969:6969
    networks:
      - account_net
    volumes:
      - /hsipl_account_system
      
    command: sh -c "npm install && npm run dev"

volumes: 
  backend_data:

networks:
  account_net:

