version: "0.1"
services:
    backend:
        restart: always
        build: .
        ports:
          -  3003:3003
        links:
          - mongo
        volumes:
          - .:/usr/src/app
    mongo:
        image: mongo
        ports:
          - 27017:27017
        volumes: 
          - mongodbdata:/data/db

        