version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: hsipl206
      MYSQL_DATABASE: hsipl
      security_opt:
        - seccomp:unconfined
      volumes:
        - /var/lib/docker/volumes/myvolume/_data
      ports:
        - 3306:3306
      networks:
        - account_net


  backend:
    build: .
    restart: always
    environment:
      MODE: dev
      PORT: 6969
      DEV_USERNAME: hsipl
      DEV_PASSWORD: hsipl206
      DEV_HOST: db
      DEV_PORT: 3306
      DEV_DB: dev_db

    links:
      - db
    ports:
      - 6969:6969
    networks:
      - account_net
    volumes:
      - /hsipl_account_system
      
    command: sh -c "npm install && npm run dev"

volumes: 
  backend_data

networks:
  account_net:
    driver: bridge
