version: "0.1"
services:
    backend:       
        build: .
        restart: always
        ports:
          -  3003:3000
        links:
          - mongo
        volumes:
          - ../hsipl_account_system:/usr/src/app
          - /usr/src/app/node_modules
        
    mongo:
        image: mongo
        restart: always
        ports:
          - 27017:27017
        volumes: 
          - ./mongodbdata:/data/db

        
